### ISSUE TITLE
CvBridge not working

### ISSUE THREAD

**Issue by kaalessi** [omrirz/pyrosenv#1]
Thank you for this awesome package. It does not seem like cv_bridge works with pyrosenv.

I am importing it as `from pyrosenv.cv_bridge import CvBridge` and receiving an error saying: `ModuleNotFoundError: No module named 'pyrosenv.cv_bridge'`. It is possible I am just not importing it correctly.

If this has not yet been implemented, are there any plans to? I am sure there are others that would like to see support for cv_bridge too.

Thanks!

**Comment by omrirz** [comment]
You are correct.
I will add cv_bridge 🙂

**Comment by kaalessi** [comment]
@omrirz Awesome! Thank you so much!

**Comment by omrirz** [comment]
@kaalessi check it out now it should work.
`pip install --upgrade pyrosenv`
